sonar.projectKey=AthletiaFrontend
sonar.projectName=AthletiaFrontend
sonar.sources=src
sonar.tests=src/__tests__
sonar.exclusions=node_modules/**,dist/**,coverage/**,src/__tests__/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info